version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleet-app
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: admin1234
      POSTGRES_USERNAME: admin
      POSTGRES_DATABASE_NAME: fleets
      APP_PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - fleet-net

  postgres:
    image: postgres:15
    container_name: fleet-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: fleets
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fleet-net

volumes:
  postgres-data:

networks:
  fleet-net:
